#pragma once

#define TAPPING_TERM 180
#define PERMISSIVE_HOLD
// #define HOLD_ON_OTHER_KEY_PRESS

#define COMBO_TERM 20
#define COMBO_MUST_TAP_PER_COMBO
#define COMBO_TERM_PER_COMBO

#define SPLIT_TRANSPORT_SYNC_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE

#define RGB_DISABLE_WHEN_USB_SUSPENDED true
// Reduce scan load
#define RGB_MATRIX_LED_PROCESS_LIMIT 4
#define RGB_MATRIX_LED_FLUSH_LIMIT 26

