#pragma once

#define TAPPING_TERM_PER_KEY
#define TAPPING_TERM 180

#define QUICK_TAP_TERM 0
#define PERMISSIVE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS

#define COMBO_TERM 20
#define COMBO_MUST_TAP_PER_COMBO
#define COMBO_TERM_PER_COMBO

#define RGBLIGHT_SPLIT
// #define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
// #define SPLIT_LED_STATE_ENABLE
// #define SPLIT_MODS_ENABLE
