DEFAULT_FOLDER = splitkb/aurora/sweep/rev1
CONVERT_TO = liatris

VPATH += keyboards/gboards/

REPEAT_KEY_ENABLE = yes
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
SEND_STRING_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes

RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor

#Feature not used
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
TAP_DANCE_ENABLE = no
LEADER_ENABLE = no
KEY_OVERRIDE_ENABLE = no
RGB_MATRIX_ENABLE = no
